apiVersion: v1
kind: Service
metadata:
  name: send-notification-service
spec:
  selector:
    app: send-notification
  ports:
  - protocol: "TCP"
    port: 6011
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-notification
spec:
  selector:
    matchLabels:
      app: send-notification
  replicas: 4
  template:
    metadata:
      labels:
        app: send-notification
    spec:
      containers:
      - name: send-notification
        image: send-notification:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000