apiVersion: v1
kind: Service
metadata:
  name: confirm-consignment-service
spec:
  selector:
    app: confirm-consignment
  ports:
  - protocol: "TCP"
    port: 6071
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: confirm-consignment
spec:
  selector:
    matchLabels:
      app: confirm-consignment
  replicas: 4
  template:
    metadata:
      labels:
        app: confirm-consignment
    spec:
      containers:
      - name: confirm-consignment
        image: confirm-consignment:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000